### ISSUE TITLE
Video is not working 

### ISSUE THREAD

**Issue by sharadchauhan0504** [bakkenbaeck/Viewer#117] opened 2017-09-04 07:17 UTC
Hi,

I am using this library to show photos and videos, photos are working fine but video is not.
All i can hear the audio with image but no audio.
Any idea why this is happening ? Same video is working in Viewer sample code. I am using pod version of viewer.

**Comment by 3lvis** [comment] 2017-09-04 08:31
Hi @skdevil,

Could you help us by providing a sample project to reproduce this issue?

Best,

**Comment by sharadchauhan0504** [comment] 2017-09-04 09:18
This project is too big to share. Can you list the possible reasons ? Like if delegate is the problem or any architecture. I am using unity in my app.

**Comment by 3lvis** [comment] 2017-09-04 09:41
The reason could be that there's a flag missing in the Info plist that allows connections but that would just not load, if you are getting audio with image but no movement then must be something else.

**Comment by 3lvis** [comment] 2017-09-04 09:47
I can't provide another suggestion without a way of reproducing it, works fine on my side. Maybe you can share the URL privately? I'm 3lvis on Twitter.

**Comment by skdevil** [comment] 2017-09-04 09:50
okay thanks.

**Comment by skdevil** [comment] 2017-09-04 10:45
Check your twitter. And one more thing, while opening and closing the viewables there is animation whose centre is that viewable. but that is also not working for me.

**Comment by 3lvis** [comment] 2017-09-09 21:25
Fixed, the issue was that the frame wasn't set correctly in @skdevil's project.

**Closed as completed by 3lvis** 2017-09-09 21:25 UTC

**Comment by twentyoneisawesome** [comment] 2018-10-03 10:04
Hi @3lvis ,
i encountered similar issue.
click 'play' button there is audio with image, but no video.
may i know how you fix the issue you mentioned about 'frame'?
tks.
